version: "3.8"

services:
  backend:
    build: ./src/backend
    ports:
      - "4000:4000"
    restart: always

  frontend:
    build: ./src/frontend
    ports:
      - "4001:4001"
    restart: always
    environment:
      - BACKEND_BASE_URL=backend:4000
    depends_on:
      - backend
